version: "3.5"

services:
  blog:
    image: ${CI_REGISTRY_IMAGE}:${CI_IMAGE_TAG}
    ports:
      - 8080:8080
    environment:
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      SECRET: ${SECRET}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
